const data =  {
    ".html": "text/html",
    ".zip": "application/zip",
    ".htm":  "text/html",
    ".css":  "text/css",
    ".js":   "text/javascript",
    ".png":  "image/png",
    ".jpeg": "image/jpeg",
    ".jpg":  "image/jpeg",
    ".gif":  "image/gif",
    ".webp": "image/webp",
    ".pdf":  "application/pdf",
    ".txt":  "text/plain",
    ".svg":  "image/svg+xml",
    ".xml":  "application/xml",
    ".ttf":  "application/x-font-ttf",
    ".woff": "application/x-font-woff",
    ".mp3":  "audio/mpeg",
    ".mp4":  "video/mp4",
    ".ogg":  "application/ogg",
    ".ogv":  "video/ogg",
    ".oga":  "audio/ogg",
    ".avi":  "video/avi",
    ".wav":  "audio/x-wav",
    ".webm": "video/webm",
    ".zip":  "application/x-compressed",
    ".bin":  "application/octet-stream",
    ".json": "text/javascript",
    ".wasm": "application/wasm",
    ".ico":  "image/x-icon",
    ".swf":  "application/x-shockwave-flash",
    ".woff2":"font/woff2",
    ".map":  "application/json",
    ".eot":  "application/vnd.ms-fontobject",
}

const cache = {
    ".html": "text/html",
    ".htm":  "text/html",
    ".pdf":  "application/pdf",
    ".txt":  "text/plain",
    ".css":  "text/css",
    ".xml":  "application/xml",
    ".bin":  "application/octet-stream",
    ".json": "text/javascript",
    ".wasm": "application/wasm",
    ".map":  "application/json",
};

const gzip = {
    ".html": "text/html",
    ".zip": "application/zip",
    ".htm":  "text/html",
    ".txt":  "text/plain",
    ".svg":  "image/svg+xml",
    ".css":  "text/css",
    ".ico":  "image/x-icon",
    ".xml":  "application/xml",
    ".ttf":  "application/x-font-ttf",
    ".js":   "text/javascript",
    ".json": "text/javascript",
    ".eot":  "application/vnd.ms-fontobject",
};

module.exports={data,cache,gzip}
