#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/engine-services.conf"
OUTPUT_FILE="${SCRIPT_DIR}/nginx-engine-upstream.conf"

if [ ! -f "$CONFIG_FILE" ]; then
  echo "Missing config: $CONFIG_FILE" >&2
  exit 1
fi

. "$CONFIG_FILE"
: "${ENGINE_API_PORTS:?Missing ENGINE_API_PORTS in $CONFIG_FILE}"

read -r -a api_ports <<< "$ENGINE_API_PORTS"
if [ "${#api_ports[@]}" -eq 0 ]; then
  echo "ENGINE_API_PORTS is empty in $CONFIG_FILE" >&2
  exit 1
fi

tmp_file="$(mktemp)"
{
  echo "# Generated by engine/generate-nginx-upstream.sh. Do not edit manually."
  echo "# Nginx upstream for zero-downtime engine API restarts."
  echo "# Include this in your nginx config and ensure it matches your engine server name."
  echo
  echo "upstream chessil_engine_api {"
  for port in "${api_ports[@]}"; do
    echo "    server 127.0.0.1:${port} max_fails=2 fail_timeout=5s;"
  done
  echo "    keepalive 64;"
  echo "}"
  echo
  echo "server {"
  echo "    server_name sf0.chessil.com;"
  echo
  echo "    server_tokens off;"
  echo
  echo "    location / {"
  echo "        proxy_pass http://chessil_engine_api;"
  echo "        include proxy_params;"
  echo
  echo "        proxy_http_version 1.1;"
  echo "        proxy_set_header Connection \"\";"
  echo "    }"
  echo
  echo "    listen [::]:443 ssl ipv6only=on; # managed by Certbot"
  echo "    listen 443 ssl; # managed by Certbot"
  echo "    ssl_certificate /etc/letsencrypt/live/sf0.chessil.com/fullchain.pem; # managed by Certbot"
  echo "    ssl_certificate_key /etc/letsencrypt/live/sf0.chessil.com/privkey.pem; # managed by Certbot"
  echo "    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot"
  echo "    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot"
  echo "}"
  echo
  echo "server {"
  echo "    if (\$host = sf0.chessil.com) {"
  echo "        return 301 https://\$host\$request_uri;"
  echo "    } # managed by Certbot"
  echo
  echo "    listen 80;"
  echo "    listen [::]:80;"
  echo "    server_name sf0.chessil.com;"
  echo "    return 404; # managed by Certbot"
  echo "}"
} > "$tmp_file"

mv "$tmp_file" "$OUTPUT_FILE"
echo "Wrote $OUTPUT_FILE"
